/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.xl351.battleship;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.PrintStream;
import java.io.Reader;
import java.io.InputStreamReader;

public class App {
  final TextPlayer player1;
  final TextPlayer player2;
  /**
   * Constructs a app with the borad, input source reader and ouput printstream
   * @param theBoard is the {@link Board}.
   * @param view is the text view of the board to display.
   * @param input source reader and ouput printstream are the remaining two parameters
   */

  public App(TextPlayer player1, TextPlayer player2) {
    this.player1 = player1;
    this.player2 = player2;
  }
  /*
    this function is used to initialize the strat print situation
   */
  public void doPlacementPhase() throws IOException{
    this.player1.doPlacementPhase();
    this.player2.doPlacementPhase();
  }

 
  public static void main(String[] args) throws IOException{
    Board<Character> b1 = new BattleShipBoard<Character>(10, 20,'X');
    Board<Character> b2 = new BattleShipBoard<Character>(10, 20,'X');
    BufferedReader input = new BufferedReader(new InputStreamReader(System.in));
    V1ShipFactory factory = new V1ShipFactory();
    TextPlayer p1 = new TextPlayer("A", b1, input, System.out, factory);
    TextPlayer p2 = new TextPlayer("B", b2, input, System.out, factory);
    App app = new App(p1, p2);
    
    //App app = new App(b,new InputStreamReader(System.in),System.out);
    app.doPlacementPhase();
  }
    
}













